### ISSUE TITLE
Yank v0.2.0 and roll back master to v0.1.x

### ISSUE THREAD

**Issue by japaric** [japaric/as-slice#4]
## Background

In PR #3 the `generic-array` dependency was semver bumped and v0.2.0 of this
crate was released just to include that change.

In general, I prefer to avoid making a new minor release (AKA semver bump) of an
"interface" crate, which main role is providing a trait for crates to
inter-operate, because it causes the ecosystem to be split in two. For example,
for `aligned` to work with `as-slice` v0.2.x (PR japaric/aligned#6) I would need
to semver bump the `aligned` crate (i.e. release v0.4.0). Then `cortex-m` to
work with that new version of `aligned` would need also a semver bump. You can
see how this produces a cascade of semver bumps across the ecosystem.

## Proposal

In the case of PR #3, the goal of supporting `generic-array` v0.13.x could have
been achieved without a semver bump. So I propose we support that crate on the
v0.1.x line and yank v0.2.0.

### Bump the MSRV

(MSRV = Minimum Supported Rust Version)

Due to the `generic-array` dependency, `as-slice` v0.1.0 has an effective MSRV of
1.19.0; on the other hand `as-slice` v0.2.0 has an effective MSRV of 1.31.0.

In this first alternative, the approach would be release a v0.1.2 of `as-slice`
that depends on *both* `generic-array` v0.12.x and v0.13.x. This approach bumps
the MSRV of v0.1.0 from 1.19 to 1.31 in v0.1.2, which *is* a breaking change.
*However*, we can get away with the MSRV bump because there's no guaranteed
MSRV; MSRV is not documented therefore there's no guaranteed MSRV.

### Cargo feature

The other option is to support `generic-array` v0.13.x in v0.1.2 behind an
opt-in Cargo feature, e.g. `ga13`. Enabling this feature makes `as-slice` v0.1.2
support *both* v0.12.x and v0.13.x of `generic-array`. Enabling the Cargo
feature does bump the MSRV but this is *not* a breaking change because it's
an opt-in bump.

---

> Isn't depending on two `generic-array`s bad for compilation time?

No, there's hardly any difference in compilation time between compiling
`generic-array` once or twice. I measured `cargo clean; cargo build`-ing this
crate and I got 2.64 s +- 0.5s for both configurations, so if there's any
difference is within standard deviation.

> Isn't yanking v0.2.0 a "breaking change"?

No, it's not a breaking change according to the Rust project's concept of
guaranteed stability. Crates that depend on v0.2.0 *published* on crates.io will
continue to use version v0.2.0 and thus continue to compile. On the other hand,
*unpublished* crates, which can be modified by the person who's compiling them,
will indeed break but can be easily fixed by subbing v0.2.0 for v0.1.2.

> But builds will break!

Sure, but the CI builds of *unpublished* crates also break whenever new warnings
are introduced in `rustc` and you were using `#[deny(warnings)]`. This breakage
is along the same line and still within Rust's concept of guaranteed stability
of *published* crates, which all crates are expected to follow (e.g. by
following semver).

---

This is not a pain-free change but I think some short-term pain is a better alternative than a long-term ecosystem split and a cascade of semver bump.

Thoughts? @korken89 
cc @burrbull

**Comment by korken89** [comment]
I think this is good, I was from the start going to simply bump the patch.
It has my approval.

**Comment by burrbull** [comment]
:+1:

**Comment by korken89** [comment]
@japaric Will you perform the process?

**Comment by japaric** [comment]
> @japaric Will you perform the process?

See PR #5
