### ISSUE TITLE
usize overflow compilation error due to the `array` macro for targets <= 16bit

### ISSUE THREAD

**Issue by BeneSim** [japaric/as-slice#8]
On targets with 16bit for `usize` or less, the compilations fails due to the overflow of usize due to the shift by 16 https://github.com/japaric/as-slice/blob/9240346ebc12f09f59af10538ea7948b4d023062/src/lib.rs#L169

I noticed this while trying to use the heapless library with an atmega328p. If you want to stick to the implementations up to `1 << 16` it could be a better option to split the `array!` macro call into several and guard them with `#[cfg(target_pointer_width = " ...")]`. I'll fire up a PR for that ;)

Compilation error is something like that
```
error[E0080]: evaluation of constant value failed
   --> /home/bisbarn/.cargo/registry/src/github.com-1ecc6299db9ec823/as-slice-0.1.3/src/lib.rs:169:102
    |
169 |     250, 251, 252, 253, 254, 255, 256, 1 << 9, 1 << 10, 1 << 11, 1 << 12, 1 << 13, 1 << 14, 1 << 15, 1 << 16
    |                                                                                                      ^^^^^^^ attempt to shift left by 16_i32 which would overflow
```

**Comment by korken89** [comment]
Now merged and fixed
